datype: val

# path
dataset_cfg_path: ./configs/dataset/synth_g.yaml
output_dir: ./preoutputs

model:
  target: sgm.modules.encoders.fsf_model.FSFModel
  params:
    ckpt_path: ./epoch=59-step=300000.ckpt

    emb_dim: 256
    n_ref_style: 12
    n_trans_layers: 12
    ca_n_heads: 8
    ca_dim_head: 64
    c_encoder_params:
      ch: 64
      ch_mult: [1, 2, 4, 8]
      num_res_blocks: 5
      resolution: 128
      attn_resolutions: [32]
    s_encoder_params:
      ch: 64
      ch_mult: [1, 2, 4, 8]
      num_res_blocks: 5
      resolution: 128
    decoder_params:
      ch: 64
      ch_mult: [1, 2, 4, 8]
      num_res_blocks: 5
      resolution: 128
      attn_resolutions: [32]

# runtime
batch_size: 4
num_workers: 0
shuffle: True
gpu: 0
max_iter: 100
