model:
  target: sgm.models.diffusion.DiffusionEngine
  params:
    input_key: image
    opt_keys:
      - t_attn
      - t_norm
      - ctrl_model
    scale_factor: 0.18215
    disable_first_stage_autocast: True

    denoiser_config:
      target: sgm.modules.diffusionmodules.denoiser.DiscreteDenoiser
      params:
        num_idx: 1000
        weighting_config:
          target: sgm.modules.diffusionmodules.denoiser_weighting.EpsWeighting
        scaling_config:
          target: sgm.modules.diffusionmodules.denoiser_scaling.EpsScaling
        discretization_config:
          target: sgm.modules.diffusionmodules.discretizer.LegacyDDPMDiscretization

    network_config:
      target: sgm.modules.diffusionmodules.openaimodel.ControlledUNetModel
      params:
        in_channels: 9
        out_channels: 4
        ctrl_channels: 1
        model_channels: 320
        attention_resolutions: [4, 2, 1]
        save_attn_type: [t_attn]
        save_attn_layers: [output_blocks.6.1]
        num_res_blocks: 2
        channel_mult: [1, 2, 4, 4]
        num_head_channels: 64
        use_linear_in_transformer: True
        transformer_depth: 1
        t_context_dim: 8192

    conditioner_config:
      target: sgm.modules.GeneralConditioner
      params:
        ucg_keys: [c_ref, s_ref]
        emb_models:
          # textual crossattn cond
          - is_trainable: True
            ucg_rate: 0.1
            input_keys: [c_ref, s_ref, ref_len]
            emb_key: t_crossattn
            target: sgm.modules.encoders.modules.FSFReferenceEmbedder2
            params:
              ckpt_path: ./checkpoints/encoders/FSF/epoch=28-step=45298.ckpt
              emb_dim: 256
              n_ref_style: 12
              n_trans_layers: 12
              ca_n_heads: 8
              ca_dim_head: 64
              c_encoder_params:
                ch: 64
                ch_mult: [1, 2, 4]
                num_res_blocks: 4
                resolution: 64
                attn_resolutions: [32]
              s_encoder_params:
                ch: 32
                ch_mult: [1, 2, 4, 8]
                num_res_blocks: 2
                resolution: 64
          # ctrl cond
          - is_trainable: False
            input_keys: [ctrl]
            emb_key: ctrl
            target: sgm.modules.encoders.modules.IdentityEncoder
          # concat cond
          - is_trainable: False
            input_keys: [mask]
            emb_key: concat
            target: sgm.modules.encoders.modules.SpatialRescaler
            params:
              multiplier: 0.125
          - is_trainable: False
            input_keys: [masked]
            emb_key: concat
            target: sgm.modules.encoders.modules.LatentEncoder
            init_model: True
            params:
              scale_factor: 0.18215

    first_stage_config:
      target: sgm.models.autoencoder.AutoencoderKLInferenceWrapper
      params:
        ckpt_path: ./checkpoints/vaes/vae_inpainting_2.safetensors
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          attn_type: vanilla-xformers
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [1, 2, 4, 4]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    loss_fn_config:
      target: sgm.modules.diffusionmodules.loss.FullLoss # StandardDiffusionLoss
      params:
        lambda_local_loss: 0.05
        g_kernel_size: 3
        g_sigma: 1.0
        min_attn_size: 32