model:
  target: sgm.models.diffusion.DiffusionEngine
  params:
    opt_keys:
      - attn1
      - norm1
      - t_attn
      - t_norm
      - ctrl_model
    input_key: image
    scale_factor: 0.18215
    disable_first_stage_autocast: True

    denoiser_config:
      target: sgm.modules.diffusionmodules.denoiser.DiscreteDenoiser
      params:
        num_idx: 1000

        weighting_config:
          target: sgm.modules.diffusionmodules.denoiser_weighting.EpsWeighting
        scaling_config:
          target: sgm.modules.diffusionmodules.denoiser_scaling.EpsScaling
        discretization_config:
          target: sgm.modules.diffusionmodules.discretizer.LegacyDDPMDiscretization

    network_config:
      target: sgm.modules.diffusionmodules.openaimodel.ControlledUNetModel
      params:
        in_channels: 9
        out_channels: 4
        ctrl_channels: 1
        model_channels: 320
        attention_resolutions: [4, 2, 1]
        save_attn_type: [t_attn]
        save_attn_layers: [output_blocks.6.1]
        num_res_blocks: 2
        channel_mult: [1, 2, 4, 4]
        num_head_channels: 64
        use_linear_in_transformer: True
        transformer_depth: 1
        t_context_dim: 1024
        share: True

    conditioner_config:
      target: sgm.modules.GeneralConditioner
      params:
        emb_models:
          # textual crossattn cond
          - is_trainable: False
            ucg_rate: 0.1
            input_key: c_ref
            emb_key: t_crossattn
            target: sgm.modules.encoders.modules.SwinReferenceEmbedder
            params:
              img_size: 224
              ckpt_path: ./checkpoints/encoders/SwinT/swin_base_patch4_window7_224/default/ckpt_epoch_120.pth
          # ctrl cond
          - is_trainable: False
            input_key: ctrl
            emb_key: ctrl
            target: sgm.modules.encoders.modules.IdentityEncoder
          # mask cond
          - is_trainable: False
            input_key: mask
            emb_key: mask
            target: sgm.modules.encoders.modules.SpatialRescaler
            params:
              in_channels: 1
              multiplier: 0.125
          # style cond
          - is_trainable: False
            input_key: s_ref
            emb_key: s_ref
            target: sgm.modules.encoders.modules.LatentEncoder
            init_model: True
            params:
              scale_factor: 0.18215
          # concat cond
          - is_trainable: False
            input_key: mask
            target: sgm.modules.encoders.modules.SpatialRescaler
            params:
              in_channels: 1
              multiplier: 0.125
          - is_trainable: False
            input_key: masked
            target: sgm.modules.encoders.modules.LatentEncoder
            init_model: True
            params:
              scale_factor: 0.18215

    first_stage_config:
      target: sgm.models.autoencoder.AutoencoderKLInferenceWrapper
      params:
        ckpt_path: ./checkpoints/vaes/vae_inpainting_2.safetensors
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          attn_type: vanilla-xformers
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [1, 2, 4, 4]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    loss_fn_config:
      target: sgm.modules.diffusionmodules.loss.StandardDiffusionLoss # StandardDiffusionLoss
      # params:
      #   seq_len: 24
      #   kernel_size: 3
      #   gaussian_sigma: 1.0
      #   min_attn_size: 16
      #   lambda_local_loss: 0.01