target: CTWGlyphDataset
params:

  editing: True
  data_root: /data/zhaoym/UDiffText/CTW
  std_font_path: ./dataset/utils/fonts/google-font/NotoSansSC-Regular.ttf

  min_seg_ratio: 0.00024
  max_seg_aspect: 2.5
  seq_len: 24
  ref_size: 64
  n_ref_style: 12
  
  refresh: False
  freq: 10